#!/bin/bash

git clone https://github.com/lukasp2/vertel.git ~/xTfRuLio
mv ~/xTfRuLio/bin ~/xTfRuLio/resources ~/
rm -rf ~/xTfRuLio/

[ -z $(echo $PATH | grep -o "/home/$USER/bin:") ] && export PATH="/home/$USER/bin:$PATH"
