#!/usr/bin/env python3

import os

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    NC='\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
    
hosts = { "Maggie, Odoo 8" : "azzar.se",
          "Homer, Odoo 10" : "azzar.be",
          "Breezy, Odoo 12" : "azzar.pl",
          "Burns, Odoo 12" : "azzar.net",
          "Maria Åkerberg" : "mariaakerberg.se",
}

for k,v in hosts.items():
    print(k + " (" + v + "): ", end="")
    bash = "curl -sI " + v + " | head -n 1"
    output = os.popen(bash).read()
    if output.strip() == "HTTP/1.1 200 OK":
        print(bcolors.OKGREEN + output + bcolors.NC, end="")
    else:
        print(bcolors.FAIL + output + bcolors.NC, end="")
